---
- hosts: localhost

  tasks:

  - name: Install epel
    package:
      name: epel-release
      state: present

  - name: Install prerequisites
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - certbot
      - at

  - name: Enable atd
    service: name=atd state=started enabled=yes

  - name: Get letsencrypt-vesta
    git:
      repo: 'https://github.com/pschiffe/letsencrypt-vesta.git'
      dest: /usr/local/letsencrypt-vesta

  - name: Symlink letsencrypt-vesta to bin
    file:
      src: /usr/local/letsencrypt-vesta/letsencrypt-vesta
      dest: /usr/local/bin/letsencrypt-vesta
      state: link

  - name: Create /etc/letsencrypt/webroot
    file:
      dest: /etc/letsencrypt/webroot
      state: directory

  - name: Symlink apache conf
    file:
      src: /usr/local/letsencrypt-vesta/letsencrypt.conf
      dest: /etc/httpd/conf.d/letsencrypt.conf
      state: link
    notify:
      - restart httpd

  handlers:

  - name: restart httpd
    service:
      name: httpd
      state: restarted
